apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc

  source:
    repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    targetRevision: 9.29.1
    helm:
      values: |
        cloudProvider: aws
        awsRegion: eu-west-1
        autoDiscovery:
          clusterName: shviki-fitness-prod-eks

        serviceAccount:
          create: false
          name: cluster-autoscaler

        extraArgs:
          cluster-name: shviki-fitness-prod-eks
          node-group-auto-discovery: "asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/shviki-fitness-prod-eks"
          skip-nodes-with-local-storage: "false"
          skip-nodes-with-system-pods: "false"
          expander: least-waste

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
