apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    targetRevision: 9.29.1
    helm:
      valueFiles:
        - ../../environments/prod/values.yaml   # 👈 still using prod
      valuesObject:
        autoDiscovery:
          clusterName: shviki-fitness-prod-eks
        awsRegion: eu-west-1
        rbac:
          serviceAccount:
            create: false
            name: cluster-autoscaler
        nodeSelector: {{ .Values.systemNodeSelector.nodeSelector }}
        tolerations: {{ .Values.systemNodeSelector.tolerations }}

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
