apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes/autoscaler.git
    targetRevision: master
    path: charts/cluster-autoscaler
    helm:
      parameters:
        - name: autoDiscovery.clusterName
          value: shviki-fitness-prod-eks        # match module.eks.cluster_name
        - name: awsRegion
          value: eu-west-1
        - name: rbac.serviceAccount.create
          value: "true"
        - name: rbac.serviceAccount.name
          value: "cluster-autoscaler"
        - name: rbac.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn
          value: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/prod-cluster-autoscaler
        - name: cloudProvider
          value: aws
        - name: image.tag
          value: v1.30.0
        - name: extraArgs.balance-similar-node-groups
          value: "true"
        - name: extraArgs.skip-nodes-with-system-pods
          value: "false"
        - name: extraArgs.expander
          value: least-waste
        - name: extraArgs.v
          value: "4"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
