apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shviki-fitness
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kingofgrow/shviki_fitness
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: sh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
