apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shviki-fitness
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Kingofgrow/shviki-fitness
    targetRevision: main
    path: helm/helm-chart
    helm:
      valueFiles:
        - ../../environments/prod/values.yaml   

  destination:
    server: https://kubernetes.default.svc
    namespace: sh

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
